name: eip1559
description: EIP-1559 Ethereum and Web3 market fee and gas estimation.
version: 0.5.0
repository: https://github.com/xclud/dart_eip1559
homepage: https://pwa.ir

environment:
  sdk: '>=2.12.0 <3.0.0'

# Add regular dependencies here.
dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
